Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyGame in c:\users\cdfri\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.5.2)
Requirement already satisfied: Matplotlib in c:\users\cdfri\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.8.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\cdfri\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\cdfri\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\cdfri\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Matplotlib) (4.49.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\cdfri\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Matplotlib) (1.4.5)
Requirement already satisfied: numpy<2,>=1.21 in c:\users\cdfri\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\cdfri\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\cdfri\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\cdfri\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\cdfri\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\cdfri\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.7->Matplotlib) (1.16.0)
